title: Shadab Nazmi # your name (or website title) here
<h4>New Delhi, India</h4><br></br>
logo:  "https://i.ibb.co/j9KNrPs/resume-shadab-nazmi.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
 
 <h3>Journalist | Visual and Data Journalism</h3>
 <br><br>
 <a href="https://www.linkedin.com/in/shadabnazmi/">Connect on LinkedIn</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
