title: Shadab Nazmi # your name (or website title) here
logo: "https://raw.githubusercontent.com/shadabnazmi/sayhello/master/Shadab_profile.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Journalist | Visual and Data Journalism
 
  <a href="https://www.linkedin.com/in/shadabnazmi/">Connect on LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
