title: Shadab Nazmi # your name (or website title) here
logo:  "https://i.ibb.co/j9KNrPs/resume-shadab-nazmi.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
 New Delhi, India
 <h3>Journalist | Visual and Data Journalism</h3>
 <a href="https://www.linkedin.com/in/shadabnazmi/">Connect on LinkedIn</a><br></br>
 See my <a href="https://drive.google.com/file/d/1Reuo8VzEUOhEsJG2_KAzuAOpGo2xuYU9/view?usp=share_link">resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
